import './globals.css'
import type { Metadata } from 'next'
import { ReactNode } from 'react'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'
import Signin from '../components/Signin'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({  children }: { children: ReactNode }) {
  const isAuthenticaded = cookies().has('token')

  return (
    <html lang="pt-br">
      <body className={inter.className}>{isAuthenticaded ? children : <Signin />}</body>
    </html>
  )
}
