export default function Agendamentos() {
  return (
    <div className=" h-full w-full ">
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
      <p>Ola</p>
    </div>
  )
}
